---
abstract: 'Find home dir of a project'
author:
  - 'Hiroki Honda <cside.story@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-ProjectHome
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  File::ProjectHome:
    file: lib/File/ProjectHome.pm
    version: 0.02
requires:
  Path::Class: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/Cside/File-ProjectHome/issues
  homepage: https://github.com/Cside/File-ProjectHome
  repository: git://github.com/Cside/File-ProjectHome.git
version: 0.02
x_contributors:
  - 'tokubass <tomi21110@gmail.com>'
